web/router.ex
defmodule DdsBlog.Router do
  use DdsBlog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", DdsBlog do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    get "/:slug", PostController, :show
  end

  # Other scopes may use custom stacks.
  # scope "/api", DdsBlog do
  #   pipe_through :api
  # end
end

lib/dds_blog/endpoint.ex
defmodule DdsBlog.Endpoint do
  use Phoenix.Endpoint, otp_app: :dds_blog

  socket "/socket", DdsBlog.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :dds_blog, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_dds_blog_key",
    signing_salt: "0e3d64A2"

  plug DdsBlog.Router
end

web/controllers/page_controller.ex
defmodule DdsBlog.PageController do
  use DdsBlog.Web, :controller

  def index(conn, _params) do
    {:ok, posts} = DdsBlog.Repo.list()
    render conn, "index.html", posts: posts
  end
end

web/controllers/post_controller.ex
defmodule DdsBlog.PostController do
  use DdsBlog.Web, :controller

  def show(conn, %{"slug" => slug}) do
    case DdsBlog.Repo.get_by_slug(slug) do
      {:ok, post} -> render(conn, "show.html", post: post)
      :not_found -> not_found(conn)
    end
  end

  def not_found(conn) do
    conn
    |> put_status(:not_found)
    |> render(DdsBlog.ErrorView, "404.html")
  end
end

web/views/error_view.ex
defmodule DdsBlog.ErrorView do
  use DdsBlog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule DdsBlog.LayoutView do
  use DdsBlog.Web, :view
end

web/views/page_view.ex
defmodule DdsBlog.PageView do
  use DdsBlog.Web, :view
end

web/views/post_view.ex
defmodule DdsBlog.PostView do
  use DdsBlog.Web, :view
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello DdsBlog!</title>
    <link href='//fonts.googleapis.com/css?family=Raleway:400,300,600' rel='stylesheet' type='text/css'>

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">

  </head>

  <body>
    <div class="container">
      <nav class="navbar">
        <div class="container">
          <ul class="navbar-list">
            <li class="navbar-item"><a class="navbar-link" href="/">ElixirDose: A Dose of Elixir Programming Language</a></li>
          </ul>
        </div>
      </nav>

      <section class="header">
        <h2 class="title"><a href="http://elixirdose.com/">ElixirDose</a></h2>
        <p>Journal of the overlooked tiny bits in young programming language. Will update weekly or two, as a way to build the habit of writing something on a regular basis. Authored by <a href="https://twitter.com/rizafahmi22" target="_blank">Riza</a> and <a href="https://twitter.com/augiedb" target="_blank">Augie</a> as Editor In Chief.</p>

        <form action="http://elixirdose.us4.list-manage2.com/subscribe/post?u=73c2706174b7f2703c432c70c&amp;id=f7b2717e3a" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate="" _lpchecked="1">
          <div class="row">
            <div class="six columns">
              <input class="u-full-width" type="email" placeholder="A dose to your inbox!" name="EMAIL" id="mce=EMAIL">
            </div>
            <div class="six columns">
              <button type="submit" class="button-primary">Engage!</button>
            </div>
          </div>
        </form>
      </section>


      <hr />
      <div class="row" style="padding-top: 20px">
        <!-- blog posts go here -->
        <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
        <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

        <%= render @view_module, @view_template, assigns %>



      </div>

      <hr />
      <footer>
        <div class="contaier">
          <div class="row">
            <div class="one-third column">
              &nbsp;
            </div>
            <div class="one-third column">
              Powered By <a href="https://github.com/rizafahmi/dds-blog" target="_blank">DDS Blog Engine</a>
            </div>
            <div class="articles one-third column">
              <a href="#">All Articles</a>
            </div>
          </div>
        </div>
      </footer>

    </div>


    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<%= for post <- @posts do %>
  <article class="row">
    <div class="col-xs-4 col-xs-offset-4">
      <h2><%= post.title %></h2>
      <!-- <p><%= Timex.format!(post.date, "{Mshort} {D} {YYYY}") %></p> -->
      <p><%= post.intro %></p>
      <p><a class="button button-primary" href="<%= post_path(@conn, :show, post.slug) %>">Read</a></p>
    </div>
  </article>
<% end %>

web/templates/post/show.html.eex
<article>
  <h1><%= @post.title %></h1>
  <p><%= Timex.format!(@post.date, "{Mshort} {D} {YYYY}") %></p>
  <%= raw(@post.content) %>
</article>
<p><a class="button" href="<%= page_path(@conn, :index) %>">&laquo; Back </a></p>